name: sdrive-frontend

services:
  frontend-dev:
    image: sdrive-frontend:dev
    pull_policy: never
    container_name: sdrive-frontend-dev
    build:
      context: ..
      dockerfile: docker/dockerfile
    profiles:
      - builder
      - dev
    ports:
      - "4000:3000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  frontend-stg:
    image: sdrive-frontend:stg
    pull_policy: never
    container_name: sdrive-frontend-stg
    build:
      context: ..
      dockerfile: docker/dockerfile
    profiles:
      - builder
      - stg
    ports:
      - "4001:3000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    
  frontend-prd:
    image: sdrive-frontend:prd
    pull_policy: never
    container_name: sdrive-frontend-prd
    build:
      context: ..
      dockerfile: docker/dockerfile
    profiles:
      - builder
      - prd
    ports:
      - "4002:3000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped