import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import App from "./App";
import { SessionProvider } from "./contexts/SessionContext";
import { SettingsProvider } from "./contexts/SettingsContext";
import { RuntimeProvider } from "./contexts/RuntimeContext";
import { LogicalFoldersProvider } from "./contexts/LogicalFolders";
import { TasksProvider } from "./contexts/TasksContext";

// Read the nonce generated by Nginx from the meta tag
const nonceMeta = document.querySelector('meta[property="csp-nonce"]');
const nonce = nonceMeta?.getAttribute("content") || undefined;

// Create the Emotion cache with the nonce
// We ignore the placeholder during local development when Nginx isn't replacing it
const muiCache = createCache({
  key: "mui",
  nonce: nonce === "NONCE_PLACEHOLDER" ? undefined : nonce,
});

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <CacheProvider value={muiCache}>
      <BrowserRouter basename={import.meta.env.VITE_APP_BASE_NAME || ""}>
        <SettingsProvider>
          <RuntimeProvider>
            <SessionProvider>
              <LogicalFoldersProvider>
                <TasksProvider>
                  <App />
                </TasksProvider>
              </LogicalFoldersProvider>
            </SessionProvider>
          </RuntimeProvider>
        </SettingsProvider>
      </BrowserRouter>
    </CacheProvider>
  </React.StrictMode>,
);
